---
title: "p8105_hw5_yg3096"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(ggplot2)
library(dplyr)
set.seed(123)
```

## Problem 1
```{r}
check <- function(n) {
         any(duplicated(sample.int(365, size = n, replace = TRUE)))
}

# For group size of 2-50, run simulation 10000 times for each size
n_size <- 2:50
prob <- numeric(length(n_size))
for (i in seq_along(n_size)) {
    n <- n_size[i]
    prob[i] <- mean(replicate(10000, check(n)))
}
sim <- data.frame(n = n_size, prob = prob)

# Plot showing probability and group size
sim |>
    ggplot(aes(x = n, y = prob)) + geom_line() + geom_point() +
    geom_hline(yintercept = 0.5) +
    labs(title = "Probability that people have duplicate birthday", 
         x = "Group size (n)", y = "Estimated probability")
```

The probability of more than one people share the same birthday increases  
rapidly as group size grows, and this probability exceeds 50% at group size of  
around 23.

## Problem 2
```{r}
n <- 30
sigma <- 5
n_mu <- 0:6
alpha <- 0.05

# Simulation for a certain mu_true, return estimate and p-value
simulate <- function(mu_true) {
            x <- rnorm(n, mean = mu_true, sd = sigma)
            tt <- t.test(x, mu = 0)
            c(estimate = unname(tt$estimate), p.value = tt$p.value, 
              mu_true = mu_true)
}

# Simulation for all mu_true
result_list <- vector("list", length(n_mu))
for (i in seq_along(n_mu)) {
    mu <- n_mu[i]
    one_mu <- replicate(5000, simulate(mu), simplify = FALSE)
    result_list[[i]] <- bind_rows(one_mu)
}
# 7*5000 rows with 3 columns, estimate, p-value and mu_true 
sim_raw <- bind_rows(result_list)

# Calculate power
power_df <- sim_raw |>
            group_by(mu_true) |>
            summarise(power = mean(p.value < alpha), .groups = "drop")

# Calculate estimate mean
estimate_df <- sim_raw |>
               group_by(mu_true) |>
               summarise(mean_est = mean(estimate), 
                         mean_est_reject = mean(estimate[p.value < alpha]),
                         .groups = "drop")

# Plot of power and true mean
power_df |>
         ggplot(aes(x = mu_true, y = power)) + geom_line() + geom_point() +
         labs(title = "Power and true mean (one-sample t, n=30, σ=5)",
              x = "True mean (μ)", y = "Power")
```